# Generated by Django 6.1.1 on 2026-09-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INITIATOR', 'Initiator'), ('APPROVER', 'Approver'), ('ADMIN', 'Administrator')], default='INITIATOR', max_length=20),
        ),
    ]
