# Generated by Django 6.1.1 on 2026-09-24 11:46

from django.db import migrations

def convert_employee_to_initiator(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    User.objects.filter(role="EMPLOYEE").update(
        role="INITIATOR"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(
            convert_employee_to_initiator,
            migrations.RunPython.noop,
        ),
    ]