# Generated by Django 6.1.1 on 2026-09-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_convert_employee_to_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('INITIATOR', 'Initiator'), ('ADMIN', 'Administrator')], default='INITIATOR', max_length=20),
        ),
    ]
