# Generated by Django 6.1.1 on 2026-09-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_approvalauthority'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalauthority',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_authorities', to='departments.department'),
        ),
    ]
