# Generated by Django 6.1.1 on 2026-09-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_authority_department'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalauthority',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_authorities', to='departments.department'),
        ),
    ]
