# Generated by Django 6.1.1 on 2026-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
