# Generated by Django 6.1.1 on 2026-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0002_alter_notesheet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_FOR_RESPONSE', 'Waiting for Response'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
