# Generated by Django 6.1.1 on 2026-09-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0003_alter_notesheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
