# Generated by Django 6.1.1 on 2026-09-27 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('notesheets', '0004_notesheet_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesheetReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_serial', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notesheet_reference_sequences', to='departments.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('department', 'year'), name='unique_notesheet_reference_sequence')],
            },
        ),
    ]
