# Generated by Django 6.1.1 on 2026-09-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0006_backfill_reference_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FINANCE', 'Finance'), ('HR', 'Human Resources'), ('PROCUREMENT', 'Procurement'), ('ADMINISTRATION', 'Administration'), ('TECHNICAL', 'Technical')], default='GENERAL', max_length=30),
        ),
    ]
