# Generated by Django 6.1.1 on 2026-09-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0007_notesheet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('IMMEDIATE', 'Immediate')], default='NORMAL', max_length=20),
        ),
    ]
