# Generated by Django 6.1.1 on 2026-09-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0008_notesheet_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesheet',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_FOR_RESPONSE', 'Waiting for Response'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20),
        ),
    ]
