# Generated by Django 6.1.1 on 2026-09-25 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0001_initial'),
        ('workflow', '0002_workflowreviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workflowassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('notesheet',), name='unique_active_assignment_per_notesheet'),
        ),
    ]
