# Generated by Django 6.1.1 on 2026-09-27 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0001_initial'),
        ('workflow', '0003_workflowassignment_unique_active_assignment_per_notesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposition', to='workflow.workflowassignment')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to=settings.AUTH_USER_MODEL)),
                ('notesheet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposition', to='notesheets.notesheet')),
            ],
        ),
    ]
