# Generated by Django 6.1.1 on 2026-09-27 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0002_alter_notesheet_status'),
        ('workflow', '0004_disposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesheetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sequence_number', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('COMMENT', 'Comment'), ('RESPONSE', 'Response'), ('CLARIFICATION_REQUEST', 'Clarification Request')], default='COMMENT', max_length=30)),
                ('response_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notesheet_comments', to=settings.AUTH_USER_MODEL)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='notesheets.notesheet')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='workflow.notesheetcomment')),
            ],
            options={
                'ordering': ['sequence_number'],
                'constraints': [models.UniqueConstraint(fields=('notesheet', 'sequence_number'), name='unique_comment_sequence_per_notesheet')],
            },
        ),
    ]
