# Generated by Django 6.1.1 on 2026-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_notesheetcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheetcomment',
            name='author_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notesheetcomment',
            name='author_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
