# Generated by Django 6.1.1 on 2026-09-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheets', '0008_notesheet_priority'),
        ('workflow', '0007_backfill_comment_author_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, null=True)),
                ('actor_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('action_type', models.CharField(choices=[('NOTESHEET_CREATED', 'Notesheet Created'), ('NOTESHEET_DISPATCHED', 'Notesheet Dispatched'), ('REVIEWER_ASSIGNED', 'Reviewer Assigned'), ('COMMENT_ADDED', 'Comment Added'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('RESPONSE_SUBMITTED', 'Response Submitted'), ('REVIEW_FORWARDED', 'Review Forwarded'), ('APPROVAL_GRANTED', 'Approval Granted'), ('APPROVAL_REJECTED', 'Approval Rejected')], max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('notesheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='notesheets.notesheet')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
