# Generated by Django 6.1.1 on 2026-09-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action_type',
            field=models.CharField(choices=[('NOTESHEET_CREATED', 'Notesheet Created'), ('NOTESHEET_DISPATCHED', 'Notesheet Dispatched'), ('REVIEWER_ASSIGNED', 'Reviewer Assigned'), ('COMMENT_ADDED', 'Comment Added'), ('CLARIFICATION_REQUESTED', 'Clarification Requested'), ('RESPONSE_SUBMITTED', 'Response Submitted'), ('REVIEW_FORWARDED', 'Review Forwarded'), ('APPROVAL_GRANTED', 'Approval Granted'), ('APPROVAL_REJECTED', 'Approval Rejected'), ('NOTESHEET_FINALIZED', 'Notesheet Finalized')], max_length=40),
        ),
    ]
