# Generated by Django 6.1.1 on 2026-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_auditevent_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='approver_department_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='disposition',
            name='approver_department_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='disposition',
            name='approver_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='disposition',
            name='approver_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
